// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmlgusykdigxskqxpqyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tbGd1c3lrZGlneHNrcXhwcXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzU2OTksImV4cCI6MjA2OTIxMTY5OX0.MLTaXroP3P07g_jW8YUB1ivQy9lqaIZ6QbZX3Vn-yQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});